## other configuration excluded from example...
exclude_patterns:
  - "node_modules/"
  - ".nyc_output"
  - "coverage"
  - "**.test.ts"
  - ".env"
  - ".env.test"
  - "**/*.json"
  - "**/*.spec.ts"
  - "test/"
  - "src/scripts/"
  - "src/migration/"
  - "src/domain/"
  - "src/repository/"
  - "**/vendor/"

version: "2"